# Generated by Django 4.2.4 on 2023-08-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garantia',
            name='fecha_final',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='fecha_inicial',
            field=models.DateField(),
        ),
    ]
