# Generated by Django 4.2.4 on 2023-08-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_garantia_fecha_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garantia',
            name='fecha_final',
        ),
        migrations.RemoveField(
            model_name='garantia',
            name='fecha_inicial',
        ),
    ]
