# Generated by Django 4.2.4 on 2023-08-27 22:20

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_remove_garantia_fecha_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantia',
            name='fecha_final',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garantia',
            name='fecha_inicial',
            field=models.DateField(default=datetime.datetime(2023, 8, 27, 22, 20, 24, 271618, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
